language: python
python:
  - "3.5"
  - "3.6"

notifications:
 email: false
install:
 - pip install numpy
 - pip install scipy
 - pip install matplotlib
script:
#проверка на то, что под python 3.5 всё работает ок
  - python -m py_compile problem-1.py
  - python -m py_compile problem-2.py
  - python -m py_compile problem-3.py
